# Generated by Django 4.2.9 on 2025-03-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('api_key', models.CharField(max_length=255)),
                ('api_password', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=4084)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
